### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tejus0** [Sas2k/Lemon#5]
Hey @Sas2k i want to make your footer more designer. So please assign me this issue.

**Comment by Sas2k** [comment]
hello @tejus0 what do you mean "footer" please clarify.
also was this issue meant for https://github.com/Sas2k/Lemon-CLI ?

**Comment by Sas2k** [comment]
@tejus0 please respond, if you do not respond or clarify on what you meant, I might have to close this issue since of inactivity

**Comment by tejus0** [comment]
@Sas2k i misunderstood the layout. The design is good. You can close the issue

**Comment by Sas2k** [comment]
@tejus0 ok?
