### ISSUE TITLE
[FEATURE] Containerisation of the entire framework.

### ISSUE THREAD

**Issue by rexdivakar** [Sas2k/Lemon#9]
Hi Team, what do you think of containerising the entire app so it can be deployed easily? I would love to implement that feature if agreed.

**Comment by Sas2k** [comment]
Hmm... I wonder if contenarizing a library would be a good thing. If this was an app or of sorts it would be nice.

**Comment by rexdivakar** [comment]
i thought this was a full standby app with wrappers to access, anyways noproblem.
